SampleProject/Controllers/CarerPaymentController.cs
/*
' Copyright (c) 2017  Blueclover Consulting Ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using TrustonTap.Common;
using TrustonTap.Common.Models;
using TrustonTap.Common.Services.CarerService;
using TrustonTap.Common.Services.LoggingService;
using TrustonTap.Common.Services.PaymentService;
using TrustonTap.Common.Services.StatementService;

namespace TrustonTap.Web.Controllers
{
    [Authorize]
    [ControllerMetadata("Manage Carer Payments", "Index")]
    public class CarerPaymentController : BaseController
	{
        private IPaymentService paymentService;
        private IStatementService statementService;
        private ICarerService carerService;
        private ILoggingService loggingService;

        public CarerPaymentController(
            IPaymentService paymentService,
            IStatementService statementService,
            ICarerService carerService,
            ILoggingService loggingService)
        {
            this.paymentService = paymentService;
            this.statementService = statementService;
            this.carerService = carerService;
            this.loggingService = loggingService;
        }

        public ActionResult Index()
        {
            var statements = statementService.GetCarerStatementsByStatus(CarerStatementStatus.PartiallyPaid, CarerStatementStatus.SentToCarer);

            var headerInfo = new Dictionary<string, string>
            {
                { "Outstanding", statements.Sum(x => x.AmountOutstanding).ToMoney() },
                { "Total Selected", "<span id='totalSelected'>£0.00</span>" }
            };

            ViewBag.HeaderInfo = headerInfo;

            return View(statements);
        }

        public ActionResult PaymentHistory(int id)
        {
            var carer = carerService.GetCarer(id);
            var paymentHistory = paymentService.GetCarerBankTransactions(id).Where(x=>x.Successful).ToList();

            if (paymentHistory.Any())
            {
                var headerInfo = new Dictionary<string, string>
                {
                    { "Payments To Date", paymentHistory.Sum(x => Math.Abs(x.Amount)).ToMoney() },
                    { "Last Payment", paymentHistory.Max(x => x.PaymentDate).ToString("dd/MM/yyyy") }
                };

                ViewBag.HeaderInfo = headerInfo;
            }

            ViewBag.Carer = carer;

            return View(paymentHistory);
        }

        public ActionResult MakePaymentModal(int[] ids, string totalAmount)
        {
            ViewBag.TotalOutstanding = totalAmount;

            return PartialView("_MakePaymentModal", ids);
        }

        public ActionResult MakePayment(List<int> ids, string amount, string reference, int paymentMethod, string paymentDate, string notes)
        {
            var success = true;

            try
            {
                var date = DateTime.ParseExact(paymentDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                foreach (int statementId in ids)
                {
                    var statement = statementService.GetCarerStatement(statementId);

                    var paymentAmount = statementService
                        .GetCarerStatementsByCarerID(statement.CarerID)
                        .Where(x=>x.Status == CarerStatementStatus.SentToCarer)
                        .Sum(x=>x.AmountOutstanding);

                    paymentService.MakeCarerPayment(statement.CarerID, date, (PaymentMethod)paymentMethod, reference, paymentAmount, notes);
                }    
            }
            catch (Exception ex)
            {
                success = false;
                loggingService.LogException(ex);
            }

            SetFeedbackMessage(success,
                "Payment has been made.",
                "There has been an error whilst making the payment.");
            return RedirectToSamePage();
        }
    }
}

SampleProject/Views/CarerPayment/Index.cshtml
@using TrustonTap.Common;
@using TrustonTap.Common.Models;
@using GridMvc.Html;

@model List<CarerStatement>

@{
    ViewBag.Title = "Outstanding Payments Due To Carer";
    var headerInfo = ViewBag.HeaderInfo;
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<div class="dropdown">
    <button text="Action" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
        Action <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li id="makePaymentMenuItem" style="display:none">
            <a onclick="showMakePaymentModal()"><i class="fa fa-money-bill-alt"></i> Make Payment</a>
        </li>
    </ul>
</div>

@Html.Partial("_Feedback")

@Html.DisplayFor(x => headerInfo, "HeaderInfo")

@Html.Grid(Model).Columns(columns =>
{
    columns.Add(x => x.ID, "Select").Titled("<input name=\"allChk\" type=\"checkbox\" id=\"cbSelectAll\" />").SetWidth(30).RenderValueAs(x => CheckboxColumn(x)).Encoded(false).Sanitized(false).Filterable(false).Sortable(false);
    columns.Add(x => x.Reference).Titled("ToT Invoice").RenderValueAs(x => StatementColumn(x)).Encoded(false).Sanitized(false).Filterable(true).Sortable(true);
    columns.Add(x => x.CreatedDate).Titled("Statement Date").RenderValueAs(x => x.CreatedDate.ToShortDateString()).Filterable(true).Sortable(true);
    columns.Add(x => x.Carer.FormattedName).Titled("Carer").RenderValueAs(x => CarerColumn(x.Carer)).Encoded(false).Sanitized(false).Filterable(true).Sortable(true);
    columns.Add(x => x.AmountOutstanding).Titled("Amount Outstanding").RenderValueAs(x => x.AmountOutstanding.ToMoney()).Filterable(true).Sortable(true);
})

<div id="modalPlaceholder" />

@helper CarerColumn(Carer carer)
{
    <a href="@Url.Action("Details", "Carer", new { id = carer.ID })">@carer.FormattedName</a>
}

@helper StatementColumn(CarerStatement statement)
{
    <a href="@Url.Action("DownloadDocument", "Document", new { id = statement.DocumentID})">@statement.Reference</a>
}

@helper CheckboxColumn(CarerStatement statement)
{
    <text>
        <input type="checkbox" data-amount="@statement.AmountOutstanding" class="toggleable" value="@statement.ID" />
    </text>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $("#cbSelectAll").change(function () {
            toggleAllCheckboxes()
        });

        $("input:checkbox").change(function () {
            var total = 0
            $("input:checkbox:checked.toggleable").each(function () {
                var v = $(this).data("amount");
                total += parseFloat(v);
            });
            $("#totalSelected").html("£" + total.toFixed(2));
            if (total > 0) {
                $("#makePaymentMenuItem").show();
            } else {
                $("#makePaymentMenuItem").hide();
            }
        });
    </script>
}

SampleProject/Views/CarerPayment/PaymentHistory.cshtml
@using TrustonTap.Common;
@using TrustonTap.Common.Models;
@using GridMvc.Html;

@model List<BankTransaction>

@{
    var carer = (User)ViewBag.Carer;
    ViewBag.Title = "Carer Payment History For " + carer.ToString();
    var headerInfo = ViewBag.HeaderInfo;
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

@Html.DisplayFor(x => headerInfo, "HeaderInfo")

@Html.Grid(Model).Columns(columns =>
{
    columns.Add(x => x.ID).Titled("Payment ID").RenderValueAs(x => x.ID.ToString()).Filterable(true).Sortable(true);
    columns.Add(x => x.Reference).Titled("Reference").RenderValueAs(x => x.Reference).Filterable(true).Sortable(true);
    columns.Add(x => x.Amount).Titled("Payment Amount").RenderValueAs(x => Math.Abs(x.Amount).ToMoney()).Filterable(true).Sortable(true);
    columns.Add(x => x.PaymentMethod).Titled("Payment Method").RenderValueAs(x => x.PaymentMethod.GetDescription()).Filterable(true).Sortable(true);
    columns.Add(x => x.PaymentDate).Titled("Payment Date").RenderValueAs(x => x.PaymentDate.ToShortDateString()).Filterable(true).Sortable(true);
}).WithPaging(20)

SampleProject/Views/CarerPayment/_MakePaymentModal.cshtml
@using TrustonTap.Common.Models;

@{
    string total = ViewBag.TotalOutstanding;
}

@model int[]

@using (Html.BeginForm("MakePayment", "CarerPayment", FormMethod.Post))
{
    <!-- Modal -->
    <div id="paymentModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                @using (Html.BeginCollectionItem("ids"))
                {
                    foreach (int i in Model)
                    {
                        <input id="Ids" name="Ids" value="@i.ToString()" type="hidden">
                    }
                }
                @Html.Hidden("Amount", total)
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Make Payment</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Amount</label>
                        @total
                    </div>
                    <div class="form-group">
                        <label>Payment Method</label>
                        @Html.CustomEnumDropDownList("paymentMethod", typeof(PaymentMethod), new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Reference</label>
                        @Html.TextBox("reference", null, new { @class = "form-control", maxlength = "50" })
                    </div>
                    <div class="form-group">
                        <label>Payment Date</label>
                        @Html.TextBox("paymentDate", DateTime.Now.ToString("dd/MM/yyyy"), new { required = true, @class = "datepicker form-control" })
                    </div>
                    <div class="form-group">
                        <label>Notes</label>
                        @Html.TextArea("notes", new { @class = "form-control", maxlength = "1000" })
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info pull-left" data-dismiss="modal"><i class="fa fa-times fa-md"></i> Close</button>
                    <button id="btnSave" type="submit" class="btn btn-info"><i class="fa fa-save fa-md"></i> Save</button>
                </div>
            </div>
        </div>
    </div>
}