SampleProject/Controllers/AuditController.cs
/*
' Copyright (c) 2017  Blueclover Consulting Ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Web.Mvc;
using TrustonTap.Common.Services.AuditService;
using TrustonTap.Web.ViewModels;

namespace TrustonTap.Web.Controllers
{
    [Authorize]
    [ControllerMetadata("Audit History")]
    public class AuditController : BaseController
    {
        private IAuditService auditService;

        public AuditController(IAuditService auditService)
        {
            this.auditService = auditService;
        }

		public ActionResult Index(AuditLogSearchViewModel model)
        {
            if(model == null)
            {
                model = new AuditLogSearchViewModel();
            }

            model.Results = auditService.SearchAuditHistory(model.SearchString, model.EventType, model.DateFrom, model.DateTo);

            return View(model);
        }
	}
}

SampleProject/Controllers/CarerController.cs
/*
' Copyright (c) 2017  Blueclover Consulting Ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TrustonTap.Common;
using TrustonTap.Common.Services.BookingService;
using TrustonTap.Common.Services.CarerService;
using TrustonTap.Common.Services.LoggingService;
using TrustonTap.Common.Services.MessagingService;
using TrustonTap.Common.Services.PaymentService;
using TrustonTap.Common.Services.StatementService;
using TrustonTap.Common.Services.TimesheetService;
using TrustonTap.Web.ViewModels;

namespace TrustonTap.Web.Controllers
{
    [Authorize]
    [ControllerMetadata("Carers", "Index")]
    public class CarerController : BaseController
	{
        private IPaymentService paymentService;
        private IBookingService bookingService;
        private IStatementService statementService;
        private ITimesheetService timesheetService;
        private ICarerService carerService;
        private ILoggingService loggingService;
        private IMessagingService messagingService;

        public CarerController(
            IPaymentService paymentService,
            IStatementService statementService,
            ITimesheetService timesheetService,
            IBookingService bookingService,
            ICarerService carerService,
            ILoggingService loggingService,
            IMessagingService messagingService)
        {
            this.paymentService = paymentService;
            this.statementService = statementService;
            this.timesheetService = timesheetService;
            this.carerService = carerService;
            this.loggingService = loggingService;
            this.messagingService = messagingService;
            this.bookingService = bookingService;
        }

        public ActionResult Index()
        {
            var carers = paymentService.GetOutstandingCreditorsList();

            var headerInfo = new Dictionary<string, string>
            {
                { "Payments To Date", carers.Sum(x => x.Key.PaymentSummary.PaymentsToDate).ToMoney() },
                { "Outstanding", carers.Sum(x => x.Key.PaymentSummary.Balance).ToMoney() },
            };

            ViewBag.HeaderInfo = headerInfo;

            return View(carers);
        }

        public ActionResult Details(int id)
        {
            var carer = carerService.GetCarer(id);
            var payments = paymentService.GetCarerPayments(id, null, null, null);
            var timesheets = timesheetService.GetTimesheets(id, null, null, null, null, null, null, null);
            var bookings = bookingService.GetBookingsForCarer(id);
            var messages = messagingService.GetSmsMessagesByUser(id);

            var availabilityLastUpdated = carerService.GetCarerAvailability(id).Max(x => x.UpdatedDate)?.ToString("dd/MM/yyyy");
            var headerInfo = new Dictionary<string, string>
            {
                { "Address", Utilities.FormatAddress(true,
                        carer.AddressLine1,
                        carer.AddressLine2,
                        carer.AddressLine3,
                        carer.Town,
                        carer.Postcode)},

                { "Telephone", carer.Phone },
                { "Email", $"<a href=\"mailto:{carer.Email}\">{carer.Email}</a>"},
                {"Payments To Date", payments.Sum(x => x.AmountPaid).ToMoney() },
                {"Outstanding", payments.Sum(x => x.AmountOutstanding).ToMoney() },
                {"Availability Last Updated", String.IsNullOrEmpty(availabilityLastUpdated) ? "Never" : availabilityLastUpdated }
            };

            ViewBag.HeaderInfo = headerInfo;
            ViewBag.Bookings = bookings;
            ViewBag.Timesheets = timesheets;
            ViewBag.SmsMessages = messages;

            return View(carer);
        }

        public ActionResult Availability(int id)
        {
            var carerHoliday = carerService.GetCarerHoliday(id);
            if (carerHoliday == null)
            {
                carerHoliday = new Common.Models.CarerHoliday()
                {
                    CarerID = id
                };
            }

            var model = new AvailabilityViewModel()
            {
                Carer = carerService.GetCarer(id),
                CarerAvailability = carerService.GetCarerAvailability(id),
                CarerHoliday = carerHoliday
            };

            var headerInfo = new Dictionary<string, string>
            {
                { "Last Updated", model.CarerAvailability.Max(x=>x.UpdatedDate)?.ToString("dd/MM/yyyy") }
            };

            ViewBag.HeaderInfo = headerInfo;

            return View(model);
        }

        public RedirectResult Impersonate(int id)
        {
            return new RedirectResult($"{ApplicationSettings.PublicWebsiteUrl}/my-trustontap?userid={id}");
        }

        [HttpPost]
        public ActionResult Availability(AvailabilityViewModel model)
        {
            var success = true;
            try
            {
                model.CarerAvailability.ForEach(x => x.UpdatedByAdmin = true);
                carerService.SaveCarerAvailability(model.CarerAvailability);
                carerService.SaveCarerHoliday(model.CarerHoliday);
            }
            catch (Exception ex)
            {
                success = false;
                loggingService.LogException(ex);
            }

            SetFeedbackMessage(success,
                "Availability has been saved.",
                "There has been an error whilst saving the availability.");

            return RedirectToSamePage();
        }

        public ActionResult Search(CarerSearchViewModel model)
        {
            model.Results = carerService.SearchCarers(model);

            return View(model);
        }

        public JsonResult SearchCarersJSON(string search)
        {
            try
            {
                var carers = carerService
                    .SearchCarers(search)
                    .Select(x => new { ID = x.ID.ToString(), Value = $"{x.DisplayName} [{x.ID}] {Utilities.FormatAddress(false, new string[] { x.AddressLine1, x.Postcode })}" });

                return Json(new { items = carers, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                loggingService.LogException(ex);

                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetCarerJSON(int id)
        {
            try
            {
                var carer = carerService
                    .GetCarer(id);

                return Json(new { result = carer, success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                loggingService.LogException(ex);

                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SampleProject/Controllers/HolidayController.cs
/*
' Copyright (c) 2017  Blueclover Consulting Ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Web.Mvc;
using TrustonTap.Common.Models;
using TrustonTap.Common.Services.HolidayService;
using TrustonTap.Common.Services.LoggingService;

namespace TrustonTap.Web.Controllers
{
    [Authorize]
    [ControllerMetadata("Holidays")]
    public class HolidayController : BaseController
    {
        private IHolidayService holidayService;
        private ILoggingService loggingService;

        public HolidayController(IHolidayService holidayService, ILoggingService loggingService)
        {
            this.holidayService = holidayService;
            this.loggingService = loggingService;
        }

        public ActionResult Index()
		{
            var model = holidayService.GetHolidays();

            return View(model);
		}

        public ActionResult EditModal(int id)
        {
            var holiday = holidayService.GetHoliday(id);

            return PartialView("_EditModal", holiday);
        }

        public ActionResult AddModal()
        {
            var holiday = new Holiday()
            {
                Date = DateTime.Now,
                Region = Region.eng
            };

            return PartialView("_EditModal", holiday);
        }

        [HttpPost]
        public ActionResult Edit(Holiday holiday)
        {
            var success = true;

            try
            {
                holidayService.SaveHoliday(holiday);
            }
            catch (Exception ex)
            {
                success = false;
                loggingService.LogException(ex);
            }

            SetFeedbackMessage(success,
                "The holiday has been amended.",
                "The holiday could not be amended.");

            return RedirectToSamePage();
        }

        public ActionResult Delete(int id)
        {
            var success = true;

            try
            {
                holidayService.DeleteHoliday(id);
            }
            catch (Exception ex)
            {
                success = false;
                loggingService.LogException(ex);
            }

            SetFeedbackMessage(success,
                "The holiday has been deleted.",
                "The holiday could not be deleted.");
            return RedirectToSamePage();
        }

        public ActionResult Download()
        {
            var success = true;
            var year = DateTime.Now.Year;
            var resultCount = 0;

            try
            {
                resultCount = holidayService.UpdateHolidays(Region.eng, year);
                resultCount += holidayService.UpdateHolidays(Region.eng, year+1);
            }
            catch (Exception ex)
            {
                success = false;
                loggingService.LogException(ex);
            }

            SetFeedbackMessage(success,
                $"The holidays for {year} and {year+1} have been updated. {resultCount} dates found.",
                $"There has been an error whilst updating holidays for {year} and {year + 1}.");
            return RedirectToAction("Index");
        }
    }
}

SampleProject/Controllers/HomeController.cs
/*
' Copyright (c) 2017  Blueclover Consulting Ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Linq;
using System.Web.Mvc;
using TrustonTap.Common;
using TrustonTap.Common.Models;
using TrustonTap.Common.Services.LoggingService;
using TrustonTap.Common.Services.PaymentService;
using TrustonTap.Common.Services.StatementService;
using TrustonTap.Common.Services.TimesheetService;

namespace TrustonTap.Web.Controllers
{
    [Authorize]
    [ControllerMetadata("Home", "Index")]
    public class HomeController : BaseController
    {
        private IPaymentService paymentService;
        private ITimesheetService timesheetService;
        private IStatementService statementService;
        private ILoggingService loggingService;

        public HomeController(
            IPaymentService paymentService,
            ITimesheetService timesheetService,
            IStatementService statementService,
            ILoggingService loggingService)
        {
            this.paymentService = paymentService;
            this.timesheetService = timesheetService;
            this.statementService = statementService;
            this.loggingService = loggingService;
        }

        public ActionResult Index()
		{
            try
            {
                ViewBag.CarerPaymentTotal = paymentService.GetCarerPayments(null, null, null, null).Sum(x => x.AmountOutstanding).ToMoney();
                ViewBag.CustomerPaymentTotal = paymentService.GetCustomerPayments(null, null, null, null, null, null, false).Sum(x => x.AmountOutstanding).ToMoney();
                ViewBag.TimesheetCount = timesheetService.GetTimesheets(null, null, null, false, null, null, null, null).Count();
                ViewBag.GoCardlessTotal = statementService
                    .GetCustomerStatementsByStatus(CustomerStatementStatus.PartiallyPaid, CustomerStatementStatus.SentToCustomer, CustomerStatementStatus.FailedPayment)
                    .Where(x => x.Booking.PaymentMethod == PaymentMethod.GoCardless)
                    .Sum(x => x.AmountOutstanding).ToMoney();
            }
            catch(Exception ex)
            {
                loggingService.LogException(ex);
            }

            return View();
		}

		public ActionResult About()
		{
			return View();
		}
	}
}

SampleProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<h3>TrustonTap Payment System</h3>
<p><Strong>Blueclover Consulting Ltd. 2017</Strong></p>
<p>Web: <a href="http://www.blueclover.co.uk">http://www.blueclover.co.uk</a></p>
<p>Email: <a href="mailto:info@blueclover.co.uk"><i class="fa fa-envelope"></i> info@blueclover.co.uk</a></p>

SampleProject/Views/Home/Index.cshtml
@using TrustonTap.Common;

@{
    ViewBag.Title = "Home";
}
<div class="row">

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "Dashboard")">
                <div class="wrimagecard-topimage_header" style="background-color: #FFE6B5">
                    <center><i class="fa fa-tachometer-alt" style="color:#FF9331"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Dashboard
                        <div class="pull-right badge" id="WrGridSystem"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "Timesheet")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(51, 105, 232, 0.1)">
                    <center><i class="fa fa-clock" style="color:#3369e8"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Timesheets
                        <div class="pull-right badge" id="WrThemesIcons" title="New Timesheets">@ViewBag.TimesheetCount</div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@ApplicationSettings.PublicWebsiteUrl/admin/test" target="_blank">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(51, 105, 232, 0.1)">
                    <center><i class="fa fa-users" style="color:#3369e8"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Carers / Customers
                        <div class="pull-right badge" id="WrGridSystem"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "Booking")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(51, 105, 232, 0.1)">
                    <center><i class="fa fa-phone" style="color:#3369e8"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Bookings
                        <div class="pull-right badge" id="WrGridSystem"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Batches", "CustomerInvoice")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(22, 160, 133, 0.1)">
                    <center><i class="fa fa-calculator" style="color:#16A085"></i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Customer Invoices
                        <div class="pull-right badge" id="WrControls"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("GoCardless", "CustomerPayment")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(130, 93, 9, 0.1)">
                    <center><i class="fa fa-credit-card" style="color:#825d09"></i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Take GoCardless Payments
                        <div class="pull-right badge" id="WrThemesIcons" title="Outstanding Amount">@ViewBag.GoCardlessTotal</div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "CustomerPayment")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(130, 93, 9, 0.1)">
                    <center><i class="fa fa-credit-card" style="color:#825d09"></i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Customer Payments
                        <div class="pull-right badge" id="WrThemesIcons" title="Outstanding Amount">@ViewBag.CustomerPaymentTotal</div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Batches", "CarerStatement")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(121, 90, 71, 0.1)">
                    <center><i class="fa fa-copy" style="color:#795a47"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Carer Invoices
                        <div class="pull-right badge" id="WrNavigation"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "CarerPayment")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(213, 15, 37, 0.1)">
                    <center><i class="fa fa-money-bill-alt" style="color:#d50f25"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Carer Payments
                        <div class="pull-right badge" id="WrForms" title="Outstanding Amount">@ViewBag.CarerPaymentTotal</div>
                    </h4>
                </div>
                </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "Audit")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(250, 188, 9, 0.1)">
                    <center><i class="fa fa-history" style="color:#fabc09"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Audit History
                        <div class="pull-right badge" id="WrForms"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@ApplicationSettings.ReportingServicesUrl" target="_blank">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(187, 120, 36, 0.1)">
                    <center><i class="fa fa-chart-line" style="color:#BB7824"></i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Reports
                        <div class="pull-right badge"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "Holiday")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(51, 105, 232, 0.1)">
                    <center><i class="fa fa-suitcase" style="color:#3369e8"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Holidays
                        <div class="pull-right badge" id="WrGridSystem"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Search", "Carer")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(178, 0, 255, 0.1)">
                    <center><i class="fa fa-search" style="color:rgb(178, 0, 255)"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Carer Search
                        <div class="pull-right badge" id="WrGridSystem"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Search", "Customer")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(22, 160, 133, 0.1)">
                    <center><i class="fa fa-search" style="color:#16A085"></i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Customer Search
                        <div class="pull-right badge" id="WrControls"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-sm-4">
        <div class="wrimagecard wrimagecard-topimage">
            <a href="@Url.Action("Index", "Maintenance")">
                <div class="wrimagecard-topimage_header" style="background-color: rgba(121, 90, 71, 0.1)">
                    <center><i class="fa fa-cogs" style="color:#795a47"> </i></center>
                </div>
                <div class="wrimagecard-topimage_title">
                    <h4>
                        Maintenance
                        <div class="pull-right badge" id="WrNavigation"></div>
                    </h4>
                </div>
            </a>
        </div>
    </div>


    <div class="col-md-3 col-sm-4">
    </div>
</div>